export const DEFAULT_INITIAL_CATEGORIES = [
  "All Products",
  "Men's Chappal",
  "Men's Khussa",
  "Women's Chappal",
  "Women's Khussa",
  "New Arrivals",
  "Featured Products"
];

export const DEFAULT_INITIAL_PRODUCTS = [
  {
    id: 'hzc-001',
    title: 'Royal Golden Zarri Peshawari Chappal',
    price: 3450,
    oldPrice: 4200,
    category: "Men's Chappal",
    sizes: [7, 8, 9, 10, 11, 12],
    stockStatus: 'in_stock',
    stockQuantity: 24,
    images: ['/src/assets/images/mens_zarri_chappal_1790507337934.jpg', '/src/assets/images/peshawari_chappal_1790507350838.jpg'],
    description: 'Masterfully hand-embroidered with pure golden zarri tilla thread on genuine full-grain black cowhide leather. Features a durable double tyre sole with comfort cushioned footbed. Perfect for weddings, Eid, and grand cultural gatherings.',
    isFeatured: true,
    isNewArrival: false,
    inRunningBanner: true,
    isActive: true,
    createdAt: '2026-09-01T10:00:00.000Z',
  },
  {
    id: 'hzc-002',
    title: 'Heritage Double Sole Peshawari Chappal - Mustard Tan',
    price: 2850,
    oldPrice: 3500,
    category: "Men's Chappal",
    sizes: [6, 7, 8, 9, 10, 11],
    stockStatus: 'in_stock',
    stockQuantity: 30,
    images: ['/src/assets/images/peshawari_chappal_1790507350838.jpg', '/src/assets/images/norozi_chappal_1790507420836.jpg'],
    description: 'Handcrafted traditional Peshawari chappal in classic mustard tan calf leather. Crafted with hand-stitched welt, heavy tyre sole for extreme longevity, and reinforced buckle strap for custom fit.',
    isFeatured: true,
    isNewArrival: false,
    inRunningBanner: true,
    isActive: true,
    createdAt: '2026-09-02T10:00:00.000Z',
  },
  {
    id: 'hzc-003',
    title: 'Men’s Royal Wedding Tilla Velvet Khussa',
    price: 3800,
    oldPrice: 4800,
    category: "Men's Khussa",
    sizes: [7, 8, 9, 10, 11],
    stockStatus: 'in_stock',
    stockQuantity: 18,
    images: ['/src/assets/images/mens_royal_khussa_1790507401990.jpg', '/src/assets/images/mens_zarri_chappal_1790507337934.jpg'],
    description: 'Regal groom khussa featuring intricate gold tilla and zari zardozi embroidery over deep royal velvet and genuine leather sole. Padded insole gives hours of effortless comfort during wedding celebrations.',
    isFeatured: true,
    isNewArrival: true,
    inRunningBanner: true,
    isActive: true,
    createdAt: '2026-09-03T10:00:00.000Z',
  },
  {
    id: 'hzc-004',
    title: 'Women’s Luxury Zarri Dabka Embroidered Khussa',
    price: 2950,
    oldPrice: 3800,
    category: "Women's Khussa",
    sizes: [36, 37, 38, 39, 40, 41],
    stockStatus: 'in_stock',
    stockQuantity: 28,
    images: ['/src/assets/images/womens_zarri_khussa_1790507365559.jpg', '/src/assets/images/womens_gold_chappal_1790507384558.jpg'],
    description: 'Authentic handcrafted Pakistani ladies khussa adorned with delicate golden zarri tilla, fine pearls, and cut-dana work. Super soft inner lining prevents shoe bites while offering royal elegance.',
    isFeatured: true,
    isNewArrival: true,
    inRunningBanner: true,
    isActive: true,
    createdAt: '2026-09-04T10:00:00.000Z',
  },
  {
    id: 'hzc-005',
    title: 'Women’s Golden Zarri Kolhapuri Festive Chappal',
    price: 2400,
    oldPrice: 3100,
    category: "Women's Chappal",
    sizes: [36, 37, 38, 39, 40, 41],
    stockStatus: 'in_stock',
    stockQuantity: 20,
    images: ['/src/assets/images/womens_gold_chappal_1790507384558.jpg', '/src/assets/images/womens_zarri_khussa_1790507365559.jpg'],
    description: 'Dainty and magnificent handcrafted women’s Zarri chappal flats with golden zari thread weave, bead embellishments, and anti-slip sole. Ideal pairing with Shalwar Kameez, Gharara, or formal wear.',
    isFeatured: false,
    isNewArrival: true,
    inRunningBanner: true,
    isActive: true,
    createdAt: '2026-09-05T10:00:00.000Z',
  },
  {
    id: 'hzc-006',
    title: 'Quetta Traditional Hand-Stitched Norozi Chappal',
    price: 3600,
    oldPrice: 4500,
    category: "Men's Chappal",
    sizes: [7, 8, 9, 10, 11, 12],
    stockStatus: 'in_stock',
    stockQuantity: 15,
    images: ['/src/assets/images/norozi_chappal_1790507420836.jpg', '/src/assets/images/peshawari_chappal_1790507350838.jpg'],
    description: 'Original Balochi Norozi Chappal master-crafted in pure heavy bridle leather with distinct elevated heel curve, double thread hand-stitching, and antique gold finish buckle.',
    isFeatured: true,
    isNewArrival: true,
    inRunningBanner: true,
    isActive: true,
    createdAt: '2026-09-06T10:00:00.000Z',
  },
  {
    id: 'hzc-007',
    title: 'Men’s Black Velvet Gold Zardozi Khussa',
    price: 3650,
    oldPrice: 4400,
    category: "Men's Khussa",
    sizes: [8, 9, 10, 11],
    stockStatus: 'limited',
    stockQuantity: 5,
    images: ['/src/assets/images/mens_royal_khussa_1790507401990.jpg', '/src/assets/images/mens_zarri_chappal_1790507337934.jpg'],
    description: 'Handmade black velvet khussa with symmetrical imperial gold thread stitching. Features soft calfskin inner and genuine leather outer sole for lasting prestige.',
    isFeatured: false,
    isNewArrival: true,
    inRunningBanner: false,
    isActive: true,
    createdAt: '2026-09-07T10:00:00.000Z',
  },
  {
    id: 'hzc-008',
    title: 'Women’s Bridal Velvet Royal Zarri Khussa',
    price: 3200,
    oldPrice: 3950,
    category: "Women's Khussa",
    sizes: [36, 37, 38, 39, 40],
    stockStatus: 'in_stock',
    stockQuantity: 14,
    images: ['/src/assets/images/womens_zarri_khussa_1790507365559.jpg', '/src/assets/images/womens_gold_chappal_1790507384558.jpg'],
    description: 'Bridal special traditional footwear with dense golden tilla zari floral motifs and soft foam cushioning. Designed to match heavy bridal attire effortlessly.',
    isFeatured: true,
    isNewArrival: true,
    inRunningBanner: true,
    isActive: true,
    createdAt: '2026-09-08T10:00:00.000Z',
  }
];
